[build]
command = "npm run build"
publish = ".netlify/dist"

[[redirects]]
from = "/_astro/*"
to = "/_astro/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200
